/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * checkin1.java
 *
 * Created on 08-Oct-2019, 22:00:44
 */

/**
 *
 * @author TOSHIBA
 */
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class checkin1 extends javax.swing.JInternalFrame {
    Connection con;
    void opencon(){
        try{
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/xiia1920", "root", "hello**231**");
            rpd.setEditable(false);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    void refresh(){
        try{
            String q = "Select cust_id,first_name,last_name,gender,nationality,email,phone_no,id_proof,room_no,check_in,status," +
                    "adults,children,check_out,bill from custinfo;";
            //String q = "Select * from custinfo;";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(q);
            DefaultTableModel dtm = (DefaultTableModel)tbl.getModel();
            while (dtm.getRowCount()>0)
                dtm.removeRow(0);
            String cid, fn, ln, rno, nat, idp, gen, ci, stat,co, adls, cldrn, em, ph, rnt;
            while (rs.next()) {
                cid = rs.getString(1);
                fn = rs.getString(2);
                ln = rs.getString(3);
                gen = rs.getString(4);
                nat = rs.getString(5);
                em = rs.getString(6);
                ph = rs.getString(7);
                idp = rs.getString(8);
                rno = rs.getString(9);
                ci = rs.getString(10);
                stat = rs.getString(11);
                adls = rs.getString(12);
                cldrn = rs.getString(13);
                co = rs.getString(14);
                rnt = rs.getString(15);
                Object nr[] = {cid, fn, ln, gen, nat, em, ph, idp, rno, ci, stat, adls, cldrn, co, rnt};
                dtm.addRow(nr);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /** Creates new form checkin1 */
    public checkin1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        rt = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        rpd = new javax.swing.JTextField();
        rent = new javax.swing.JLabel();
        rno = new javax.swing.JLabel();
        floor = new javax.swing.JComboBox();
        roomtype = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        roomno = new javax.swing.JComboBox();
        c_id = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        nat = new javax.swing.JLabel();
        idp = new javax.swing.JLabel();
        eid = new javax.swing.JLabel();
        pno = new javax.swing.JLabel();
        adlt = new javax.swing.JLabel();
        cldrn = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        adults = new javax.swing.JTextField();
        nalty = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        indt = new javax.swing.JLabel();
        outdt = new javax.swing.JLabel();
        check_in = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        children = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        id_p = new javax.swing.JComboBox();
        gen = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox();
        pet = new javax.swing.JComboBox();
        p = new javax.swing.JLabel();
        v = new javax.swing.JLabel();
        view = new javax.swing.JComboBox();
        cin = new com.toedter.calendar.JDateChooser();
        cout = new com.toedter.calendar.JDateChooser();
        background = new javax.swing.JLabel();

        setResizable(true);
        setTitle("Check-In");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        close.setFont(new java.awt.Font("Georgia Pro", 1, 15));
        close.setForeground(new java.awt.Color(0, 0, 255));
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        rt.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        rt.setForeground(new java.awt.Color(255, 255, 255));
        rt.setText("Room Type");

        f.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        f.setForeground(new java.awt.Color(255, 255, 255));
        f.setText("Floor");

        rpd.setFont(new java.awt.Font("Tahoma", 1, 14));
        rpd.setForeground(new java.awt.Color(0, 153, 51));

        rent.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        rent.setForeground(new java.awt.Color(255, 255, 255));
        rent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rent.setText("Rent per day (₹)");

        rno.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        rno.setForeground(new java.awt.Color(255, 255, 255));
        rno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rno.setText("Room Number");

        floor.setFont(new java.awt.Font("Tahoma", 1, 14));
        floor.setForeground(new java.awt.Color(0, 153, 51));
        floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorActionPerformed(evt);
            }
        });

        roomtype.setFont(new java.awt.Font("Tahoma", 1, 14));
        roomtype.setForeground(new java.awt.Color(0, 153, 51));
        roomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomtypeActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Georgia Pro", 1, 26));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HOTEL SKYLINE");
        jLabel3.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 20));
        jLabel6.setForeground(new java.awt.Color(153, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html><body><h1><u>Check-In</u></h1></body></html>");

        roomno.setFont(new java.awt.Font("Tahoma", 1, 14));
        roomno.setForeground(new java.awt.Color(0, 153, 51));
        roomno.setPreferredSize(new java.awt.Dimension(60, 20));
        roomno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoActionPerformed(evt);
            }
        });

        c_id.setFont(new java.awt.Font("Tahoma", 1, 14));
        c_id.setForeground(new java.awt.Color(0, 153, 51));

        fname.setFont(new java.awt.Font("Tahoma", 1, 14));
        fname.setForeground(new java.awt.Color(0, 153, 51));

        id.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("Customer ID");

        fn.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        fn.setForeground(new java.awt.Color(255, 255, 255));
        fn.setText("First Name");

        ln.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        ln.setForeground(new java.awt.Color(255, 255, 255));
        ln.setText("Last Name");

        nat.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        nat.setForeground(new java.awt.Color(255, 255, 255));
        nat.setText("Nationality");

        idp.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        idp.setForeground(new java.awt.Color(255, 255, 255));
        idp.setText("ID Proof");

        eid.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        eid.setForeground(new java.awt.Color(255, 255, 255));
        eid.setText("Email ID");

        pno.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        pno.setForeground(new java.awt.Color(255, 255, 255));
        pno.setText("Phone No.");

        adlt.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        adlt.setForeground(new java.awt.Color(255, 255, 255));
        adlt.setText("Adults");

        cldrn.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        cldrn.setForeground(new java.awt.Color(255, 255, 255));
        cldrn.setText("Children");

        email.setFont(new java.awt.Font("Tahoma", 1, 14));
        email.setForeground(new java.awt.Color(0, 153, 51));

        adults.setFont(new java.awt.Font("Tahoma", 1, 14));
        adults.setForeground(new java.awt.Color(0, 153, 51));

        nalty.setFont(new java.awt.Font("Tahoma", 1, 14));
        nalty.setForeground(new java.awt.Color(0, 153, 51));

        phone.setFont(new java.awt.Font("Tahoma", 1, 14));
        phone.setForeground(new java.awt.Color(0, 153, 51));

        lname.setFont(new java.awt.Font("Tahoma", 1, 14));
        lname.setForeground(new java.awt.Color(0, 153, 51));
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });

        indt.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        indt.setForeground(new java.awt.Color(255, 255, 255));
        indt.setText("Check-In Date");

        outdt.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        outdt.setForeground(new java.awt.Color(255, 255, 255));
        outdt.setText("Expected Check-Out Date");

        check_in.setFont(new java.awt.Font("Georgia Pro", 1, 15));
        check_in.setForeground(new java.awt.Color(0, 0, 255));
        check_in.setText("Check-In");
        check_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_inActionPerformed(evt);
            }
        });

        tbl.setFont(new java.awt.Font("Times New Roman", 0, 13));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cust ID", "First Name", "Last Name", "Gender", "Nationality", "Email", "Phone No.", "ID Proof", "Room No.", "Check - In", "Status", "Adults", "Children", "Check - Out", "Bill"
            }
        ));
        tbl.setName("Check-In information"); // NOI18N
        tbl.setRowHeight(18);
        tbl.setSelectionBackground(new java.awt.Color(0, 204, 204));
        jScrollPane1.setViewportView(tbl);

        children.setFont(new java.awt.Font("Tahoma", 1, 14));
        children.setForeground(new java.awt.Color(0, 153, 51));

        clear.setFont(new java.awt.Font("Georgia Pro", 1, 15));
        clear.setForeground(new java.awt.Color(0, 0, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        id_p.setFont(new java.awt.Font("Tahoma", 1, 14));
        id_p.setForeground(new java.awt.Color(0, 153, 51));
        id_p.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Passport", "Aadhar Card", "Ration Card", "Voter ID" }));
        id_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pActionPerformed(evt);
            }
        });

        gen.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        gen.setForeground(new java.awt.Color(255, 255, 255));
        gen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gen.setText("Gender");

        gender.setFont(new java.awt.Font("Tahoma", 1, 14));
        gender.setForeground(new java.awt.Color(0, 153, 51));
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        pet.setFont(new java.awt.Font("Tahoma", 1, 14));
        pet.setForeground(new java.awt.Color(0, 153, 51));
        pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petActionPerformed(evt);
            }
        });

        p.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        p.setForeground(new java.awt.Color(255, 255, 255));
        p.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        p.setText("Pet");

        v.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        v.setForeground(new java.awt.Color(255, 255, 255));
        v.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        v.setText("View");

        view.setFont(new java.awt.Font("Tahoma", 1, 14));
        view.setForeground(new java.awt.Color(0, 153, 51));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eid)
                    .addComponent(fn)
                    .addComponent(ln)
                    .addComponent(gen)
                    .addComponent(nat)
                    .addComponent(pno, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idp)
                    .addComponent(adlt)
                    .addComponent(cldrn)
                    .addComponent(id))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_id, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(fname, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(lname, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(gender, javax.swing.GroupLayout.Alignment.TRAILING, 0, 163, Short.MAX_VALUE)
                    .addComponent(nalty, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(id_p, javax.swing.GroupLayout.Alignment.LEADING, 0, 163, Short.MAX_VALUE)
                            .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(adults, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(children, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f)
                            .addComponent(rent)
                            .addComponent(rno)
                            .addComponent(v)
                            .addComponent(p)
                            .addComponent(rt))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(indt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outdt)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cout, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_in, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rpd)
                        .addComponent(roomno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(floor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roomtype, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(view, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE)))
                .addGap(214, 214, 214))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(close)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rt)
                            .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id)
                            .addComponent(c_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(fn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f)
                            .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ln)
                    .addComponent(p)
                    .addComponent(pet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gen)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(v))
                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nat)
                    .addComponent(nalty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rno)
                    .addComponent(roomno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eid)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rent)
                    .addComponent(rpd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pno)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idp)
                            .addComponent(id_p, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adults, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adlt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(children, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cldrn))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(check_in, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(indt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(outdt))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(39, 39, 39)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1190, 680);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Check In.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1320, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_closeActionPerformed

    private void floorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorActionPerformed
        // TODO add your handling code here:
        //COMBO BOX
        try{
            String q1 = (String)roomtype.getSelectedItem();
            String q2 = (String)floor.getSelectedItem();
            String q3 = "Select distinct view from rinfo where status='vacant' and room_type='"+q1+"' and floor='"+q2+"'";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(q3);
            view.removeAllItems();
            while(rs.next()){
                view.addItem(rs.getString(1));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
}//GEN-LAST:event_floorActionPerformed

    private void roomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomtypeActionPerformed
        // TODO add your handling code here:
        try{
            floor.removeAllItems();
            String q1 = (String)roomtype.getSelectedItem();
            String q2 = "Select distinct floor from rinfo where status='vacant' and room_type='"+q1+"'";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(q2);
            floor.removeAllItems();
            while(rs.next()){
                floor.addItem(rs.getString(1));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_roomtypeActionPerformed

    private void roomnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoActionPerformed
// TODO add your handling code here:
        try{
            String r = (String)roomno.getSelectedItem();
            String q = "Select rent_per_day from rinfo where room_no="+r;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(q);
            rpd.setText("");
            while(rs.next()){
            rpd.setText(rs.getString(1));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
}//GEN-LAST:event_roomnoActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_lnameActionPerformed

    private void check_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_inActionPerformed
        try{
//Extracting data from the fields
            String cid,f,l,nat,e,pno,a,c,rno,prf,gen,rent;
             cid = c_id.getText();
             f = fname.getText();
             l = lname.getText();
             nat = nalty.getText();
             e = email.getText();
             pno = phone.getText();
             a = adults.getText();
             c = children.getText();
             rno = (String)roomno.getSelectedItem();
             prf = (String)id_p.getSelectedItem();
             gen = (String)gender.getSelectedItem();
             rent = rpd.getText();
            //java.util.Date ci = cin.getDate();
            //java.util.Date co = cout.getDate();

//Get checkin and checkout date as String objects
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String ci = formatter.format(this.cin.getDate());
            String co = formatter.format(this.cout.getDate());

//Inserting values in table cust
        String q = "Insert into custinfo values('" + cid + "','" + f + "','" + l + "','" + gen + "','" + nat + "','" +
          e + "'," + pno + ",'" + prf + "'," + rno + ",'" + ci + "','Occupied'," + a + "," + c + ",'" + co + "'," + rent + ")";
            Statement stmt=con.createStatement();
            stmt.executeUpdate(q);
            refresh();
            
//Changing status to Occupied
            String q2 = "Update rinfo set status ='Occupied' where room_no= "+rno;
            stmt.executeUpdate(q2);
            refresh();
            JOptionPane.showMessageDialog(this,"Check-in Successful.");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
}//GEN-LAST:event_check_inActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        try{
//Generate and display customer id
            String q1 = "Select max(cust_id)+1 from custinfo";
            Statement stmt1 = con.createStatement();
            ResultSet rs = stmt1.executeQuery(q1);
            String cid="";
            while(rs.next())
                cid = rs.getString(1);
            c_id.setText(cid);

//Enter check-in date by default
            java.util.Date d=new java.util.Date();
            cin.setDate(d);

//Clear text fields
            fname.setText("");
            lname.setText("");
            nalty.setText("");
            id_p.setSelectedIndex(1);
            gender.setSelectedIndex(1);
            email.setText("");
            phone.setText("");
            adults.setText("");
            children.setText("");
            rpd.setText("");
            roomtype.setSelectedIndex(1);
            cout.setDate(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_clearActionPerformed

    private void id_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_id_pActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_genderActionPerformed

    private void petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petActionPerformed
// TODO add your handling code here:
        try{
            roomno.removeAllItems();
            String r = (String)roomno.getSelectedItem();
            String q1 = (String)roomtype.getSelectedItem();
            String q2 = (String)floor.getSelectedItem();
            String q3 = (String)pet.getSelectedItem();
            String q4 = "Select distinct room_no from rinfo where status='vacant' and room_type='"+q1
                    +"'and floor='"+q2+"'and pet='"+q3+"'";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(q4);
            roomno.removeAllItems();
            while(rs.next()){
                roomno.addItem(rs.getString(1));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_petActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
// TODO add your handling code here:
     try{
            roomno.removeAllItems();
            String r = (String)roomno.getSelectedItem();
            String q1 = (String)roomtype.getSelectedItem();
            String q2 = (String)floor.getSelectedItem();
            String q3 = (String)view.getSelectedItem();
            String q4 = "Select distinct pet from rinfo where status='vacant' and room_type='"+q1
                    +"' and floor='"+q2+"' and view='"+q3+"'";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(q4);
            pet.removeAllItems();
            while(rs.next()){
                pet.addItem(rs.getString(1));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
}//GEN-LAST:event_viewActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
// TODO add your handling code here:
        opencon();
        refresh();

//Enter values in room type combo box
     try{
        String q="Select distinct room_type from rinfo where status='vacant'";
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery(q);
        String r;
        while(rs.next()){
            r=rs.getString(1);
            roomtype.addItem(r);
        }

//Generate and display customer id
        String q1="Select max(cust_id)+1 from custinfo";
        Statement stmt1=con.createStatement();
        ResultSet rs1=stmt1.executeQuery(q1);
        String i="";
        while(rs.next())
            i=rs1.getString(1);
        c_id.setText(i);

//Enter check-in date by default
        java.util.Date d=new java.util.Date();
        cin.setDate(d);

}catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adlt;
    private javax.swing.JTextField adults;
    private javax.swing.JLabel background;
    private javax.swing.JTextField c_id;
    private javax.swing.JButton check_in;
    private javax.swing.JTextField children;
    private com.toedter.calendar.JDateChooser cin;
    private javax.swing.JLabel cldrn;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private com.toedter.calendar.JDateChooser cout;
    private javax.swing.JLabel eid;
    private javax.swing.JTextField email;
    private javax.swing.JLabel f;
    private javax.swing.JComboBox floor;
    private javax.swing.JLabel fn;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel gen;
    private javax.swing.JComboBox gender;
    private javax.swing.JLabel id;
    private javax.swing.JComboBox id_p;
    private javax.swing.JLabel idp;
    private javax.swing.JLabel indt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ln;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField nalty;
    private javax.swing.JLabel nat;
    private javax.swing.JLabel outdt;
    private javax.swing.JLabel p;
    private javax.swing.JComboBox pet;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel pno;
    private javax.swing.JLabel rent;
    private javax.swing.JLabel rno;
    private javax.swing.JComboBox roomno;
    private javax.swing.JComboBox roomtype;
    private javax.swing.JTextField rpd;
    private javax.swing.JLabel rt;
    private javax.swing.JTable tbl;
    private javax.swing.JLabel v;
    private javax.swing.JComboBox view;
    // End of variables declaration//GEN-END:variables

}
