/*import com.sun.org.apache.xerces.internal.impl.RevalidationHandler;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;*/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HotelManagementSystem.java
 *
 * Created on 24-Aug-2019, 17:07:26
 */

/**
 *
 * @author TOSHIBA
 */
public class HotelManagementSystem extends javax.swing.JFrame {
  /*   int x,y=100;
    @Override
public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2=(Graphics2D)g;
        Font f=new Font("Lucida Calligraphy",Font.BOLD,50);
        g2.setFont(f);
        g2.setColor(Color.WHITE);
        g2.drawString("Sunrise Galaxy Hotel",x,y);//for moving the text
try{
    Thread.sleep(50);
}
catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
}
        x+=1;//speed with which the text moves
        if(x>this.getWidth())
        x=0;
        repaint();
}*/

    /** Creates new form HotelManagementSystem */
    public HotelManagementSystem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        chkin = new javax.swing.JButton();
        rpt = new javax.swing.JButton();
        rinfo = new javax.swing.JButton();
        chkout = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        hotelicon = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOTEL SKYLINE");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        dp.setBackground(new java.awt.Color(204, 204, 255));
        dp.setForeground(new java.awt.Color(0, 0, 0));
        dp.setMinimumSize(new java.awt.Dimension(90, 50));
        dp.setOpaque(false);
        dp.setPreferredSize(new java.awt.Dimension(1019, 837));
        getContentPane().add(dp);
        dp.setBounds(240, 0, 1140, 720);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setOpaque(false);

        chkin.setBackground(new java.awt.Color(0, 0, 153));
        chkin.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        chkin.setForeground(new java.awt.Color(255, 255, 255));
        chkin.setText("Check - In");
        chkin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chkinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chkinMouseExited(evt);
            }
        });
        chkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkinActionPerformed(evt);
            }
        });

        rpt.setBackground(new java.awt.Color(0, 0, 153));
        rpt.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        rpt.setForeground(new java.awt.Color(255, 255, 255));
        rpt.setText("Report");
        rpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rptMouseExited(evt);
            }
        });
        rpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptActionPerformed(evt);
            }
        });

        rinfo.setBackground(new java.awt.Color(0, 0, 153));
        rinfo.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        rinfo.setForeground(new java.awt.Color(255, 255, 255));
        rinfo.setText("Room Information ");
        rinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rinfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rinfoMouseExited(evt);
            }
        });
        rinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rinfoActionPerformed(evt);
            }
        });

        chkout.setBackground(new java.awt.Color(0, 0, 153));
        chkout.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        chkout.setForeground(new java.awt.Color(255, 255, 255));
        chkout.setText("Check-Out");
        chkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chkoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chkoutMouseExited(evt);
            }
        });
        chkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkoutActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(0, 0, 153));
        exit.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        hotelicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Skyline.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hotelicon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(rinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(chkin, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(chkout, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(rpt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotelicon, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rinfo)
                .addGap(75, 75, 75)
                .addComponent(chkin)
                .addGap(72, 72, 72)
                .addComponent(chkout)
                .addGap(82, 82, 82)
                .addComponent(rpt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 240, 720);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background(HS).jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -20, 1450, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rinfoActionPerformed
// TODO add your handling code here:
        rinfo roominfo = new rinfo();
        roominfo.setVisible(true);
        dp.add(roominfo);

    }//GEN-LAST:event_rinfoActionPerformed

    private void chkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkinActionPerformed
// TODO add your handling code here:
        checkin1 chckin = new checkin1();
        chckin.setVisible(true);
        dp.add(chckin);
}//GEN-LAST:event_chkinActionPerformed

    private void chkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkoutActionPerformed
// TODO add your handling code here:
        checkout chckout = new checkout();
        chckout.setVisible(true);
        dp.add(chckout);
}//GEN-LAST:event_chkoutActionPerformed

    private void rptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptActionPerformed
// TODO add your handling code here:
        report reprt = new report();
        reprt.setVisible(true);
        dp.add(reprt);
}//GEN-LAST:event_rptActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
// TODO add your handling code here:
System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void rinfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rinfoMouseEntered
 // TODO add your handling code here:
        rinfo.setContentAreaFilled(true);
    }//GEN-LAST:event_rinfoMouseEntered

    private void rinfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rinfoMouseExited
// TODO add your handling code here:
         rinfo.setContentAreaFilled(false);
    }//GEN-LAST:event_rinfoMouseExited

    private void chkinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkinMouseEntered
// TODO add your handling code here:
         chkin.setContentAreaFilled(true);
    }//GEN-LAST:event_chkinMouseEntered

    private void chkinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkinMouseExited
// TODO add your handling code here:
        chkin.setContentAreaFilled(false);
    }//GEN-LAST:event_chkinMouseExited

    private void chkoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkoutMouseEntered
// TODO add your handling code here:
        chkout.setContentAreaFilled(true);
    }//GEN-LAST:event_chkoutMouseEntered

    private void chkoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkoutMouseExited
// TODO add your handling code here:
        chkout.setContentAreaFilled(false);
    }//GEN-LAST:event_chkoutMouseExited

    private void rptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rptMouseEntered
// TODO add your handling code here:
        rpt.setContentAreaFilled(true);
    }//GEN-LAST:event_rptMouseEntered

    private void rptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rptMouseExited
// TODO add your handling code here:
        rpt.setContentAreaFilled(false);
    }//GEN-LAST:event_rptMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
        

    }//GEN-LAST:event_formWindowOpened

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
// TODO add your handling code here:
        exit.setContentAreaFilled(true);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
// TODO add your handling code here:
        exit.setContentAreaFilled(false);
    }//GEN-LAST:event_exitMouseExited


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelManagementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton chkin;
    private javax.swing.JButton chkout;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JButton exit;
    private javax.swing.JLabel hotelicon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rinfo;
    private javax.swing.JButton rpt;
    // End of variables declaration//GEN-END:variables

}
