import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.*;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginHotelManagmntSys.java
 *
 * Created on 24-Aug-2019, 17:20:30
 */

/**
 *
 * @author TOSHIBA
 */
//for moving text like marquee behaviour
public class LoginHotelManagmntSys extends javax.swing.JFrame {

    private static void ImageIcon(String string) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
 int x,y=150;
    @Override
public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2=(Graphics2D)g;
        Font f=new Font("Lucida Calligraphy",Font.BOLD,50);
        g2.setFont(f);
        g2.setColor(Color.RED);
        g2.drawString("Hotel Skyline",x,y);//for moving the text
try{
    Thread.sleep(100);
}
catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
}
        x+=5;//speed with which the text moves
        if(x>this.getWidth())
        x=0;
        repaint();
}
    /** Creates new form LoginHotelManagmntSys */
    public LoginHotelManagmntSys() {
        initComponents();
        plogin.setBackground(new Color(0,0,0,100));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plogin = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        pword = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        show = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        plogin.setBackground(new java.awt.Color(0, 0, 102));
        plogin.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)), "LOGIN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Bookman Old Style", 1, 24), new java.awt.Color(255, 0, 0)))); // NOI18N
        plogin.setAlignmentX(1.0F);
        plogin.setAlignmentY(1.0F);
        plogin.setAutoscrolls(true);
        plogin.setFont(new java.awt.Font("Arial", 0, 18));
        plogin.setOpaque(false);

        name.setFont(new java.awt.Font("Georgia Pro", 1, 22));
        name.setForeground(new java.awt.Color(0, 0, 102));
        name.setText("Username");

        uname.setFont(new java.awt.Font("Times New Roman", 1, 20));
        uname.setForeground(new java.awt.Color(255, 255, 204));
        uname.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        uname.setOpaque(false);

        pword.setFont(new java.awt.Font("Georgia Pro", 1, 22));
        pword.setForeground(new java.awt.Color(0, 0, 102));
        pword.setText("Password");

        pass.setFont(new java.awt.Font("Times New Roman", 1, 20));
        pass.setForeground(new java.awt.Color(255, 255, 204));
        pass.setOpaque(false);
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });

        login.setFont(new java.awt.Font("Times New Roman", 1, 20));
        login.setForeground(new java.awt.Color(0, 153, 204));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        show.setBackground(new java.awt.Color(255, 255, 255));
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ploginLayout = new javax.swing.GroupLayout(plogin);
        plogin.setLayout(ploginLayout);
        ploginLayout.setHorizontalGroup(
            ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ploginLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(pword))
                .addGap(45, 45, 45)
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(ploginLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        ploginLayout.setVerticalGroup(
            ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ploginLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name))
                .addGap(31, 31, 31)
                .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pword)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(login)
                .addGap(34, 34, 34))
        );

        getContentPane().add(plogin);
        plogin.setBounds(120, 150, 570, 270);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 1366, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection con;
    void opencon(){
        try{
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/xiia1920","root","hello**231**");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
}
    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
//this is toogle button to show and hide the password MainFrame mf = newMainframe();
    //mf.setVisisble(true);
if(show.isSelected()){
    pass.setEchoChar((char)0);
    ImageIcon img=new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\Adi\\showpass.jpg");
    show.setIcon(img);
}
else{
    pass.setEchoChar('•');
    ImageIcon img=new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\Adi\\hidepass.jpg");
    show.setIcon(img);

}
    }//GEN-LAST:event_showActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
//this button is to login into the hotel management system
String n = uname.getText();
String pwd = new String(pass.getPassword());
if(pwd.equals("9724")&&n.equals("Aditi")){
     HotelManagementSystem mainf = new HotelManagementSystem();
     mainf.setVisible(true);
}
else{
   JOptionPane.showMessageDialog(this,"Invalid Username or Password");
uname.setText("");
pass.setText("");
}
    }//GEN-LAST:event_loginActionPerformed

    public void LoginHotelManagmentSys(Color Color){
JPanel panel = new JPanel();
plogin.setBackground(new Color(213, 134, 145, 123));
}

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
opencon();
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
/*        Splash_Screen ssf = new Splash_Screen();
        ssf.getContentPane().add(new JLabel("",new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Images\\HOTEL.gif"),SwingConstants.CENTER));
        ssf.setBounds(4500, 3000, 3200, 2900);
        ssf.setVisible(true);
        try {
                Thread.sleep(10000);
                
            } catch (InterruptedException ex) {
                Logger.getLogger(LoginHotelManagmntSys.class.getName()).log(Level.SEVERE, null, ex);
            }
            ssf.dispose();*/




       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginHotelManagmntSys().setVisible(true);


            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JLabel name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPanel plogin;
    private javax.swing.JLabel pword;
    private javax.swing.JToggleButton show;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables

}
