/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * rinfo.java
 *
 * Created on 24-Sep-2019, 21:30:49
 */

/**
 *
 * @author TOSHIBA
 */
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class rinfo extends javax.swing.JInternalFrame {
    Connection con;
      void opencon(){
        try{
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/xiia1920","root","hello**231**");
        }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    void refresh(){
        try{
            String q = "Select * from rinfo;";

//Display table based on query
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(q);
            DefaultTableModel dtm = (DefaultTableModel)tbl.getModel();
            while(dtm.getRowCount()>0){
                dtm.removeRow(0);
            }
            String rt,rno,fl,rpd,v,s,p;
            while(rs.next()){
                rno = rs.getString(1);
                rt = rs.getString(2);
                fl = rs.getString(3);
                s = rs.getString(4);
                p = rs.getString(5);
                v = rs.getString(6);
                rpd = rs.getString(7);
                Object nr[] = {rno,rt,fl,s,p,v,rpd};
                dtm.addRow(nr);
            }
        }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    /** Creates new form rinfo */
    public rinfo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        close = new javax.swing.JButton();
        roomt = new javax.swing.JLabel();
        flor = new javax.swing.JLabel();
        room_no = new javax.swing.JTextField();
        rent_pd = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rtype = new javax.swing.JComboBox();
        flr = new javax.swing.JComboBox();
        vrb = new javax.swing.JRadioButton();
        srb = new javax.swing.JRadioButton();
        status = new javax.swing.JComboBox();
        pet = new javax.swing.JComboBox();
        prb = new javax.swing.JRadioButton();
        view = new javax.swing.JComboBox();
        rtrb = new javax.swing.JRadioButton();
        flrb = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        r_perday = new javax.swing.JLabel();
        rn = new javax.swing.JLabel();
        floor = new javax.swing.JComboBox();
        roomtype = new javax.swing.JComboBox();
        add_nf = new javax.swing.JButton();
        add_nrt = new javax.swing.JButton();
        addnrcd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        pic_frame = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setResizable(true);
        setTitle("Room Information");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        delete.setFont(new java.awt.Font("Georgia Pro", 1, 15));
        delete.setForeground(new java.awt.Color(0, 0, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        close.setFont(new java.awt.Font("Georgia Pro", 1, 15));
        close.setForeground(new java.awt.Color(0, 0, 255));
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        roomt.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        roomt.setForeground(new java.awt.Color(255, 255, 255));
        roomt.setText("Room Type");

        flor.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        flor.setForeground(new java.awt.Color(255, 255, 255));
        flor.setText("Floor");

        room_no.setFont(new java.awt.Font("Tahoma", 1, 14));
        room_no.setForeground(new java.awt.Color(0, 153, 51));

        rent_pd.setEditable(false);
        rent_pd.setFont(new java.awt.Font("Tahoma", 1, 14));
        rent_pd.setForeground(new java.awt.Color(0, 153, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        rtype.setFont(new java.awt.Font("Tahoma", 1, 14));
        rtype.setForeground(new java.awt.Color(0, 153, 51));
        rtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Studio", "Deluxe", "Suite" }));
        rtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtypeActionPerformed(evt);
            }
        });

        flr.setFont(new java.awt.Font("Tahoma", 1, 15));
        flr.setForeground(new java.awt.Color(0, 153, 51));
        flr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First", "Second", "Third", "Fourth" }));
        flr.setOpaque(false);
        flr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flrActionPerformed(evt);
            }
        });

        vrb.setBackground(new java.awt.Color(255, 255, 255));
        vrb.setFont(new java.awt.Font("Tahoma", 1, 15));
        vrb.setForeground(new java.awt.Color(255, 255, 255));
        vrb.setText("View");
        vrb.setOpaque(false);
        vrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrbActionPerformed(evt);
            }
        });

        srb.setBackground(new java.awt.Color(255, 255, 255));
        srb.setFont(new java.awt.Font("Tahoma", 1, 15));
        srb.setForeground(new java.awt.Color(255, 255, 255));
        srb.setText("Status");
        srb.setOpaque(false);
        srb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srbActionPerformed(evt);
            }
        });

        status.setFont(new java.awt.Font("Tahoma", 1, 14));
        status.setForeground(new java.awt.Color(0, 153, 51));
        status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vacant", "Occupied" }));
        status.setOpaque(false);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        pet.setFont(new java.awt.Font("Tahoma", 1, 14));
        pet.setForeground(new java.awt.Color(0, 153, 51));
        pet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pet-friendly", "Non Pet-friendly" }));
        pet.setOpaque(false);
        pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petActionPerformed(evt);
            }
        });

        prb.setBackground(new java.awt.Color(255, 255, 255));
        prb.setFont(new java.awt.Font("Tahoma", 1, 15));
        prb.setForeground(new java.awt.Color(255, 255, 255));
        prb.setText("Pet");
        prb.setOpaque(false);
        prb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prbActionPerformed(evt);
            }
        });

        view.setFont(new java.awt.Font("Tahoma", 1, 14));
        view.setForeground(new java.awt.Color(0, 153, 51));
        view.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Beach", "Garden", "Sunrise", "Sunset" }));
        view.setOpaque(false);
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        rtrb.setBackground(new java.awt.Color(255, 255, 255));
        rtrb.setFont(new java.awt.Font("Tahoma", 1, 15));
        rtrb.setForeground(new java.awt.Color(255, 255, 255));
        rtrb.setText("Room Type");
        rtrb.setOpaque(false);
        rtrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtrbActionPerformed(evt);
            }
        });

        flrb.setBackground(new java.awt.Color(255, 255, 255));
        flrb.setFont(new java.awt.Font("Tahoma", 1, 15));
        flrb.setForeground(new java.awt.Color(255, 255, 255));
        flrb.setText("Floor");
        flrb.setOpaque(false);
        flrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flrbActionPerformed(evt);
            }
        });

        tbl.setFont(new java.awt.Font("Times New Roman", 0, 14));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ROOM NUMBER", "ROOM TYPE", "FLOOR", "STATUS", "PET", "VIEW", "RENT PER DAY"
            }
        ));
        tbl.setName(""); // NOI18N
        tbl.setOpaque(false);
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rtype, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtrb))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flr, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flrb))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vrb))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(srb))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prb)
                            .addComponent(pet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srb)
                    .addComponent(prb)
                    .addComponent(rtrb)
                    .addComponent(flrb)
                    .addComponent(vrb, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        r_perday.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        r_perday.setForeground(new java.awt.Color(255, 255, 255));
        r_perday.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        r_perday.setText("Rent per day");

        rn.setFont(new java.awt.Font("Georgia Pro", 1, 18));
        rn.setForeground(new java.awt.Color(255, 255, 255));
        rn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rn.setText("Room Number");

        floor.setFont(new java.awt.Font("Tahoma", 1, 14));
        floor.setForeground(new java.awt.Color(0, 153, 51));
        floor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First", "Second", "Third", "Fourth" }));
        floor.setOpaque(false);

        roomtype.setFont(new java.awt.Font("Tahoma", 1, 14));
        roomtype.setForeground(new java.awt.Color(0, 153, 51));
        roomtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Studio", "Deluxe", "Suite" }));
        roomtype.setOpaque(false);
        roomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomtypeActionPerformed(evt);
            }
        });

        add_nf.setFont(new java.awt.Font("Georgia Pro", 1, 15));
        add_nf.setForeground(new java.awt.Color(0, 0, 255));
        add_nf.setText("Add New Floor");
        add_nf.setOpaque(false);
        add_nf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_nfActionPerformed(evt);
            }
        });

        add_nrt.setFont(new java.awt.Font("Georgia Pro", 1, 15));
        add_nrt.setForeground(new java.awt.Color(0, 0, 255));
        add_nrt.setText("Add New Room Type");
        add_nrt.setOpaque(false);
        add_nrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_nrtActionPerformed(evt);
            }
        });

        addnrcd.setFont(new java.awt.Font("Georgia Pro", 1, 15));
        addnrcd.setForeground(new java.awt.Color(0, 0, 255));
        addnrcd.setText("Add New Record");
        addnrcd.setOpaque(false);
        addnrcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnrcdActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Georgia Pro", 1, 26));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HOTEL SKYLINE");
        jLabel3.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 20));
        jLabel6.setForeground(new java.awt.Color(153, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html><body><h1><u>Room Information</u></h1></body></html>");

        clear.setFont(new java.awt.Font("Georgia Pro", 1, 15));
        clear.setForeground(new java.awt.Color(0, 0, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        pic_frame.setBackground(new java.awt.Color(0, 0, 0));
        pic_frame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout pic_frameLayout = new javax.swing.GroupLayout(pic_frame);
        pic_frame.setLayout(pic_frameLayout);
        pic_frameLayout.setHorizontalGroup(
            pic_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pic_frameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );
        pic_frameLayout.setVerticalGroup(
            pic_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pic_frameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flor)
                            .addComponent(roomt)
                            .addComponent(r_perday))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(add_nf, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(add_nrt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                            .addGap(79, 79, 79))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(rent_pd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(room_no, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(pic_frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(addnrcd)
                        .addGap(104, 104, 104)
                        .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(112, 112, 112)
                        .addComponent(clear)
                        .addGap(110, 110, 110)
                        .addComponent(close)
                        .addGap(342, 342, 342))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(131, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rn)
                            .addComponent(room_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rent_pd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r_perday))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_nrt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomt))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(flor)
                            .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_nf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pic_frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addnrcd)
                    .addComponent(close)
                    .addComponent(delete)
                    .addComponent(clear))
                .addGap(266, 266, 266))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 1150, 680);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background2.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1250, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
// TODO add your handling code here:
        try{
            opencon();
            flr.setEnabled(false);
            view.setEnabled(false);
            status.setEnabled(false);
            pet.setEnabled(false);
            refresh();
//            display();
            rtrb.setSelected(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
//Displays the image of the particular view selected in combo box
        String image=(String)view.getSelectedItem();
        if(vrb.isSelected()){
     if(image.equalsIgnoreCase("Beach"))
       pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\Beach.jpg"));
     if(image.equalsIgnoreCase("Garden"))
       pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\Garden.jpg"));
     if(image.equalsIgnoreCase("Sunrise"))
       pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\Sunrise.jpg"));
     if(image.equalsIgnoreCase("Sunset"))
       pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\Sunset.jpg"));
        }
}//GEN-LAST:event_viewActionPerformed

    private void add_nrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_nrtActionPerformed
// TODO add your handling code here:
        try{
            String nr = JOptionPane.showInputDialog("Enter new Room Type:");
            if(nr!=null){
                roomtype.addItem(nr);
                roomtype.setSelectedItem(nr);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
}//GEN-LAST:event_add_nrtActionPerformed

    private void add_nfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_nfActionPerformed
// TODO add your handling code here:
        try{
            String nf = JOptionPane.showInputDialog("Enter new Floor:");
            if(nf!=null){
                floor.addItem(nf);
                floor.setSelectedItem(nf);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
}//GEN-LAST:event_add_nfActionPerformed

    private void addnrcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnrcdActionPerformed
// TODO add your handling code here:
        try{
            String rt = (String)rtype.getSelectedItem();
            String f = (String)flr.getSelectedItem();
            String v = (String)view.getSelectedItem();
            String p = (String)pet.getSelectedItem();
            String rno = room_no.getText();
            String rpd = rent_pd.getText();
            String q = "Insert into rinfo values('"+ rno + "','" + rt + "','" + f + "','Vacant','" + p + "','" + v + "',"  + rpd +")";
            Statement stmt = con.createStatement();
            stmt.executeUpdate(q);
            room_no.setText("");
            rent_pd.setText("");
            refresh();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_addnrcdActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
// TODO add your handling code here:
        try{
            String n = JOptionPane.showInputDialog("Enter the Room Number to be deleted:");
            String q = "Delete from rinfo where room_no="+n;
            Statement stmt = con.createStatement();
            stmt.executeUpdate(q);
            refresh();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void rtrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtrbActionPerformed
// TODO add your handling code here:
        try{
            if(rtrb.isSelected()){
            rtype.setEnabled(true);
            flr.setEnabled(false);
            view.setEnabled(false);
            status.setEnabled(false);
            pet.setEnabled(false);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
}//GEN-LAST:event_rtrbActionPerformed

    private void flrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flrbActionPerformed
// TODO add your handling code here:
        try{
            if(flrb.isSelected()){
            rtype.setEnabled(false);
            flr.setEnabled(true);
            view.setEnabled(false);
            status.setEnabled(false);
            pet.setEnabled(false);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_flrbActionPerformed

    private void vrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrbActionPerformed
// TODO add your handling code here:
         try{
            if(vrb.isSelected()){
            rtype.setEnabled(false);
            flr.setEnabled(false);
            view.setEnabled(true);
            status.setEnabled(false);
            pet.setEnabled(false);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_vrbActionPerformed

    private void srbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srbActionPerformed
// TODO add your handling code here:
         try{
            if(srb.isSelected()){
            rtype.setEnabled(false);
            flr.setEnabled(false);
            view.setEnabled(false);
            status.setEnabled(true);
            pet.setEnabled(false);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_srbActionPerformed

    private void prbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prbActionPerformed
// TODO add your handling code here:
         try{
            if(prb.isSelected()){
            rtype.setEnabled(false);
            flr.setEnabled(false);
            view.setEnabled(false);
            status.setEnabled(false);
            pet.setEnabled(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_prbActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
// TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_closeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
// TODO add your handling code here:
room_no.setText("");
rent_pd.setText("");
roomtype.setSelectedIndex(0);
floor.setSelectedIndex(0);
rtype.setSelectedIndex(0);
flr.setSelectedIndex(0);
view.setSelectedIndex(0);
status.setSelectedIndex(0);
pet.setSelectedIndex(0);
}//GEN-LAST:event_clearActionPerformed

    private void rtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtypeActionPerformed
//Displays the image of the particular room type selected in combo box
        String image=(String)rtype.getSelectedItem();
        if(rtrb.isSelected()){
            if(image.equalsIgnoreCase("Single"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\Single.jpg"));
            if(image.equalsIgnoreCase("Double"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\Double.jpg"));
            if(image.equalsIgnoreCase("Studio"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\Studio.jpg"));
            if(image.equalsIgnoreCase("Deluxe"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\Deluxe.jpg"));
            if(image.equalsIgnoreCase("Suite"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\Suit.jpg"));
//Displays the cost of the selected room type
        double c = 0;
        String cost=(String)rtype.getSelectedItem();
        if(cost.equalsIgnoreCase("Single"))
                c+= 2000;
        if(cost.equalsIgnoreCase("Double"))
                c+= 3000;
        if(cost.equalsIgnoreCase("Studio"))
                c+= 3500;
        if(cost.equalsIgnoreCase("Deluxe"))
                c+= 4000;
        if(cost.equalsIgnoreCase("Suite"))
                c+= 5000;
        rent_pd.setText(""+c);
        }
    }//GEN-LAST:event_rtypeActionPerformed

    private void petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petActionPerformed
//Displays the pet facility of the room
        String image=(String)pet.getSelectedItem();
        if(prb.isSelected()){
            if(image.equalsIgnoreCase("Pet-friendly"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\Pet-friendly.jpg"));
            if(image.equalsIgnoreCase("Non Pet-friendly"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\Non Pet-friendly.jpg"));
        }
    }//GEN-LAST:event_petActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
//Displays the status of the room
        String image=(String)status.getSelectedItem();
        if(srb.isSelected()){
            if(image.equalsIgnoreCase("Vacant"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\vacant.PNG"));
            if(image.equalsIgnoreCase("Occupied"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\occupied.PNG"));
        }
    }//GEN-LAST:event_statusActionPerformed

    private void roomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomtypeActionPerformed

    }//GEN-LAST:event_roomtypeActionPerformed

    private void flrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flrActionPerformed
//Displays the floor number
        String image=(String)flr.getSelectedItem();
        if(flrb.isSelected()){
            if(image.equalsIgnoreCase("First"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\1.gif"));
            if(image.equalsIgnoreCase("Second"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\2.gif"));
            if(image.equalsIgnoreCase("Third"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\3.gif"));
            if(image.equalsIgnoreCase("Fourth"))
                pic.setIcon(new ImageIcon("C:\\Users\\TOSHIBA\\Desktop\\12th\\Informatics Practices\\Project\\Hotel Features\\4.gif"));
        }
    }//GEN-LAST:event_flrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_nf;
    private javax.swing.JButton add_nrt;
    private javax.swing.JButton addnrcd;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox floor;
    private javax.swing.JLabel flor;
    private javax.swing.JComboBox flr;
    private javax.swing.JRadioButton flrb;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox pet;
    private javax.swing.JLabel pic;
    private javax.swing.JPanel pic_frame;
    private javax.swing.JRadioButton prb;
    private javax.swing.JLabel r_perday;
    private javax.swing.JTextField rent_pd;
    private javax.swing.JLabel rn;
    private javax.swing.JTextField room_no;
    private javax.swing.JLabel roomt;
    private javax.swing.JComboBox roomtype;
    private javax.swing.JRadioButton rtrb;
    private javax.swing.JComboBox rtype;
    private javax.swing.JRadioButton srb;
    private javax.swing.JComboBox status;
    private javax.swing.JTable tbl;
    private javax.swing.JComboBox view;
    private javax.swing.JRadioButton vrb;
    // End of variables declaration//GEN-END:variables

}
